query InstrumentRefData($ObjectList: [String!]) {
  DerivedContentStructuredProducts(objectIds: $ObjectList) {
    ObjectId
    SwissStampDutyTax {
      AssetTypeDescription
      IssuerDomicileText
      SwissStampDutyFlag
      TaxationComment
      TaxationType
    }
    OneTimeInterestPayment {
      InteretUniquePredominantTypeCode
    }
    SwissNationalBankReporting {
      AssetClass {
        SwissNationalBankClassification
        SwissNationalBankValue
      }
    }
    USIncomeTax {
      UnitedStatesIncomeTaxEligibilityText
      UnitedStatesIncomeTypeCode
    }
    UnitOfDelivery {
      UnitOfDeliveryCode
    }
  }
}