query InstrumentRefData($ObjectList: [String!]) {
  MuniInstrument(objectIds: $ObjectList) {
    ObjectId
    Reference {
      AdditionalCreditFlag
      AmountIssuedTotal
      AnnouncementDate
      AssetCharacteristicsCode
      AssetDuplicateCode
      AssetSetupDate
      AssetSubtypeCode
      BankQualifiedFlag
      CallableFlag
      CavMaturityAmount
      Cfi
      CouponClassCode
      CouponFloorRate
      CouponLifeCapRate
      CouponTypeCode
      CusipChangeCode
      CusipChangeDate
      DataCalculationServicesCode
      DatedDate
      DebtServiceCode
      DefeasableFlag
      DeferredInterestConversionDate
      DenominationIncrementAmount
      DenominationMinimumAmount
      DenominationTypeCode
      DtcEligibleFlag
      EsgBondFlag
      EstimatedFreeConversionFlag
      EvaluatedPriceRic
      EvaluatedQuoteId
      FinraTraceGradeCode
      FirstCouponDate
      FirstResetDate
      FungibleFlag
      GreenBondFlag
      GuaranteedFlag
      InflationProtectionFlag
      InitialPhysicalFormCode
      InstrumentClassification
      InstrumentId
      InstrumentName
      InstrumentShortName
      IssueCurrencyIsoCode
      LastCouponDateBeforeMaturity
      LastResetDate
      LetterOfCreditFlag
      MakeWholeCallFlag
      MaturityDate
      NextCallDate
      NextCallPrice
      NextParCallDate
      NextParCallPrice
      NextPayDate
      NextPutDate
      NextPutPrice
      NextResetDate
      OfferingMarketCode
      OriginalCusipTypeCode
      OriginalIssueDate
      OriginalIssueDiscountFlag
      PartialRedemptionFlag
      PerpetualFlag
      PoisonPutFlag
      PreRefundedFlag
      PreferredRic
      PrimaryCountryOfIssue
      PrivatePlacementFlag
      ProjectName
      ProspectusDate
      ProspectusOnFileFlag
      PutableFlag
      RecordDateCalendarCode
      RecordDateDays
      RedemptionValue
      ReofferDate
      ReofferFlag
      SecondaryInsuranceFlag
      SecuredFlag
      SecurityClassCode
      SecurityDescription
      SecurityDescriptionSupplementary
      SecuritySourceCode
      SeniorityCode
      SeriesName
      SettlementCalendarCode
      SettlementCalendarValue
      SettlementHolidayConventionCode
      SinkingAmortizationFlag
      SourceOfPaymentCode
      SpecialPutFlag
      StatusOfDocumentCode
      StraightBondFlag
      SuperSinkerFlag
      TaxCallFlag
      TaxStatusCode
      TermToMaturityYears
      TraceEligibleCode
    }
    Identifiers {
      EffectiveFromDate
      IdentifierCode
      IdentifierValue
      InstrumentId
    }
    AlternativeIdentifiers {
      IdentifierCode
      IdentifierValue
      InstrumentId
    }
    AmountOutstandingHistory {
      CurrecyIsoCode
      EffectiveFromDate
      FactorValue
      InstrumentId
      IssuePrice
      IssueYield
      IssuedAmount
      NetChangeAmount
      NetChangeCode
      SourceTypeCode
    }
    AssetStatus {
      AssetStatusCode
      EffectiveFromDate
      InstrumentId
    }
    CallTerms {
      CallFrequencyCode
      CallHolidayConventionCode
      CallMakeWholeSpreadRate
      CallMakeWholeTreasuryItem
      CallMaximumEquityClawbackAmount
      CallMethodCode
      CallNoticeDaysUnitCode
      CallOptionCode
      CallTermsTypeCode
      CompoundAccretedValueFlag
      FinalCallPrice
      InstrumentId
      LegNumber
      MakeWholeLegNumber
      MaximumCallNoticeDays
      MinimumCallNoticeDays
      PerpetualCallSchedule
      SpecialCallTypeCode
    }
    CallSchedule {
      CallTypeCode
      EffectiveFromDate
      EffectiveToDate
      InstrumentId
      LegNumber
      Price
    }
    ClassificationScheme {
      InstrumentId
      PropertyCode
    }
    CouponRateSchedule {
      CouponDeterminationDate
      CouponRate
      CouponRateCode
      CouponRateSourceCode
      CouponUnadjustedResetDate
      EffectiveFromDate
      InstrumentId
      MunicipalRateTypeCode
      NonAnnualCouponRate
    }
    Denomination {
      DenominationAmount
      DenominationCurrencyIsoCode
      EffectiveFromDate
      InstrumentId
      MinimumDenomAtIssuanceFlag
      MinimumDenominationFlag
    }
    Enhancements {
      AdditionalCreditTypeCode
      EffectiveFromDate
      EffectiveToDate
      EscrowAccountFlag
      GuaranteeType
      GuarantorOrganizationId
      GuarantorTypeProgramCode
      InstrumentId
      LegNumber
      LetterOfCreditExpirationDate
    }
    FundTerms {
      AdditionalPaymentPercent
      FundAmountUnitCode
      FundTypeCode
      InstrumentId
      LegNumber
      ObligationFrequencyCode
      PrimaryFundFlag
      PrincipalAllocationCode
      SinkCode
      SinkingAmortizationScheduleTypeCode
    }
    FundSchedule {
      ConversionRatio
      FundTypeCode
      InstrumentId
      LegNumber
      SinkingFundAmount
      SinkingFundDate
      SinkingFundPrice
      SkipPaymentFlag
    }
    InterestCashFlow {
      ComplexCoupon
      ComplexFloaterFlag
      ComplexReasonCode
      CompoundingPeriodCode
      ContingentCouponFlag
      CouponCapRate
      CouponClassCode
      CouponCurrencyIsoCode
      CouponDeferrableFlag
      CouponFloorRate
      CouponPaymentRuleCode
      CouponRateFormula
      DayCountCode
      HolidayConventionForCouponPaymentsCode
      HolidayConventionForRateChangeCode
      InstrumentId
      InterestEffectiveDate
      LegNumber
      PayCalendarValue
      PaymentCalendarCode
      PaymentFrequencyCode
      RateResetFrequencyCode
      RateRoundingCode
      ResetCalendarCode
      ResetCalendarValue
      ResetRuleCode
    }
    IssuanceDefinition {
      CharacterOfOfferingCode
      DateDated
      InstrumentId
      IssueAmount
      IssueCurrencyIsoCode
      IssueDate
      IssuePrice
      LegNumber
      ReofferPrice
      ReofferYield
      TotalPriceToPublicAmount
      TotalProceedsToRegistrantAmount
      YieldAtOffer
    }
    MifidInformation {
      BondType
      CofiaFlag
      ComplexFlag
      EeaEligibleFlag
      InstrumentId
      MifirIdentifierCode
      SeniorityCode
    }
    MuniDefaultSchedule {
      DefaultStatusCode
      DefaultStatusDate
      DefaultTypeCode
      EventCode
      EventDate
      EventDescription
      InstrumentId
      MaterialEventFlag
    }
    Note {
      InstrumentId
      Note
      NoteEffectiveDate
      NoteTypeCode
    }
    OriginalIssueInformation {
      AverageLifeAtOffer
      DeliveryDate
      ExtraordinaryRedemptionFlag
      InstrumentId
      InstrumentIssueYield
      InstrumentTypeCode
      IssueCurrencyIsoCode
      OriginalCharacterOfOfferingCode
      OriginalIssueAmount
      OriginalIssueComparedTo
      OriginalIssueCoupon
      OriginalIssuePrice
      OriginalYieldMaturity
      ParValue
      RemarketingDate
      RemarketingFlag
      ReofferPrice
      ReofferYield
      ShortSecurityName
      TermToMaturity
      TotalPriceToPublicAmount
      TotalProceedsToRegistrantAmount
      UseOfProceedsCategoryCode
      UseOfProceedsCode
    }
    Rating {
      EffectiveFromDate
      InstrumentId
      IssuePreliminaryRatingFlag
      IssueRating
      IssueRatingEndorsement
      IssueRatingSourceCode
      IssueRatingSourceDateCode
      IssueRatingSuffixCode
      IssueRatingUnsolicitedFlag
      IssueRatingVerifiedDate
      RatingAgencyBranchLei
      RatingAgencyEndorsedLei
    }
    OutlookRating {
      EffectiveFromDate
      EffectiveToDate
      InstrumentId
      OutlookCode
      OutlookSourceCode
    }
    RatingWatch {
      EffectiveFromDate
      EffectiveToDate
      InstrumentId
      SourceCode
      WatchCode
    }
    PrincipalDefinition {
      AlternativeCurrencyIsoCode
      BaseIndexDate
      BaseIndexValue
      BasePaymentAmount
      BasePaymentCurrencyIsoCode
      EffectiveFromDate
      HolidayConventionForIndexationFactor
      IndexationFactorCalendarCode
      IndexationFactorCalendarValue
      IndexationFactorChangeFrequencyCode
      IndexationFactorRuleCode
      InstrumentId
      LegNumber
      PrincipalAdjustmentMethodCode
      PrincipalDualCurrencyExchangeCode
      PrincipalDualCurrencyExchangeRate
    }
    PutTerms {
      InstrumentId
      LegNumber
      MaximumPutNoticeDays
      MinimumPutNoticeDays
      PerpetualPutSchedule
      PutFeeAmount
      PutFrequencyCode
      PutHolidayConventionCode
      PutMethodCode
      PutNoticeDaysUnitCode
      PutOptionCode
      PutTermsTypeCode
    }
    PutSchedule {
      EffectiveFromDate
      EffectiveToDate
      InstrumentId
      LegNumber
      Price
      PutTypeCode
    }
    RefundTerms {
      EscrowPercent
      InstrumentId
      RedeemedAmount
      RedeemedRate
      RefundDate
      RefundIssueDatedDate
      RefundPrice
      RefundTypeCode
    }
    SourceDocument {
      DocumentEffectiveDate
      DocumentSourceTypeCode
      InstrumentId
    }
    Deal{
      DealInformation {
        ActiveFlag
        DealId
        Description
        IssuerOrganizationId
        OfferTypeCode
        OfferingDate
        TotalProgramAmount
      }
      TransferAgentOrganizationId
    }
    IssuerOrganizationId
    Quotes{
      Identifier {
        CurrencyIsoCode
        CurrentFlag
        DistributionSourceCode
        GlobalRegionCode
        IdentifierSetUpDate
        IdentifierTypeCode
        IdentifierValue
        ObjectTypeCode
        PriceSourceCode
        PrimaryFlag
        QuoteId
        ScopeId
      }
      QuoteStatus {
        AdminStatus
        AdminStatusReason
        DeletedFlag
        DistributionSourceCode
        ObjectTypeId
      }
    }
  }
}