query InstrumentRefData($ObjectList: [String!]) {
  EDFInstrument(objectIds: $ObjectList) {
    ObjectId
    Reference {
      AdrSponsorType
      AdrType
      AifmdGeographicalAreaId
      AssetClassId
      AverageValueOrders
      AverageValueOrdersCurrencyId
      Bar
      BarrierLower
      BarrierTouchedDate
      BarrierUpper
      BonusActiveIndicator
      BonusLevel
      Cfi
      CfiSP
      CfiUS
      ConvertibleFlag
      CoraxPrimaryQuoteId
      CoverageType
      CumulativeFlag
      DependentIssueId
      DependentQuoteId
      DependentSharesQuantity
      DepositoryReceiptQuantity
      DepositoryReceiptRatio
      DtccEligible
      EesmIssuanceDate
      EsmaAssetClassOfTheUnderlying
      EsmaComplexInstrumentFlag
      EsmaCurrencyId
      EsmaIssuanceSize
      EsmaOptionType
      ExecutableRatioResultingShares
      ExecutableRatioSharesHeld
      ExerciseBeginDates {
        ExerciseBeginDate
      }
      ExerciseEndDates {
        ExerciseEndDate
      }
      ExerciseQuantity
      ExoticCode
      ExoticValue
      FinancialInstrumentShortNames {
        FinancialInstrumentShortName
        LanguageId
      }
      ForeignInvestorMaxPercentTotalShares
      ForeignInvestorPercentofTotalShares
      FreeFloatEuroUpperLimit
      FreeFloatEuros
      FttAppliedFlag
      InstrumentAssetType
      InstrumentCommonNames {
        InstrumentNameCommon
        LanguageId
      }
      InstrumentDAVRCSAssetClass
      InstrumentExerciseStyle
      InstrumentExpiryDate
      InstrumentId
      InstrumentIdObjectTypeId
      InstrumentIssuerOrganizationId
      InstrumentIssuerOrganizationIdObjectTypeId
      InstrumentNamesEsmaFull {
        InstrumentNameEsmaFull
      }
      InstrumentNamesShort {
        InstrumentNameShort
        LanguageId
      }
      InstrumentNdaAssetCategory
      InstrumentStatus
      IpoFlag
      IsPrimaryIssue
      KnockInOutIndicator
      ListingStatus
      NumberOfShareAllowedForForeignInvestors
      OpenEndIndicator
      OptionStrikePrice
      OptionType
      ParticipationFlag
      ParticipationNote
      Pchip
      PrivatePlacementIndicator
      RedChip
      RedeemableFlag
      RegistrationCountryId
      RemainingSharesForForeignInvestors
      RightsAllocated {
        RightsAllocated
      }
      RightsTradingEndDate
      RightsTradingStartDate
      RightsUnderlyingSharesHeld {
        RightsUnderlyingSharesHeld
      }
      Rule13FFlag
      SettlementType
      SpIssueStatus
      SubscriptionCurrencyId
      SubscriptionCurrencyObjectTypeId
      SubscriptionEndDate
      SubscriptionPrice
      SubscriptionStartDate
      TermofUnderlyingIndexEsma
      TotalSharesHeldByForeignInvestors
      UnderlingIndexNames {
        LanguageId
        UnderlyingIndexName
      }
      UnderlyingIndexNamesEsma {
        LanguageId
        UnderlyingIndexNameEsma
      }
      UnderlyingType
      VotingFlag
      WarrantAnnouncementDate
      WarrantForm
      WarrantNotes {
        WarrantNote
      }
      WarrantType
      WarrantUnderlyingType
    }
    InstrumentIdentifiers {
      IdentifierTypeId
      IdentifierData {
        IdentifierEffectiveFrom
        IdentifierValue
        PrimaryIdentifierFlag
      }
    }
    IssuerOrganizationId
    MarketCapitalizationOrganizationId
    ValuationQuote {
      ObjectId
      MarketAttributableSourceId
      Reference {
        AllocationDeliveryDay
        AssetRoot
        BarrelsPerTon
        BaseProduct
        BaseProductEsma
        BasisGapAdjusted
        BasisGapAdjustmentTrigger
        BtuPerBarrel
        CallPutOption
        CashInLieu
        CaveatEmptorFlag
        ChinaConnectEligibleType
        CommoditiesDerivativeIndicator
        CommoditiesDerivativeIndicatorEsma
        CompositeQuoteFlag
        ContractDate
        ContractType
        ContractTypeEsma
        CountryPrimaryQuoteFlag
        DailyTradingLimit
        DateOfAdmissionToTradingEsma
        DateOfRequestforAdmissionToTradingEsma
        DateofApprovalofAdmissiontoTradingEsma
        DeliveryCashSettlementLocationEsma
        DeliveryTypeEsma
        DerivativePeriodicity
        EmissionsAllowancesSubType
        EmissionsAllowancesSubTypeEsma
        ErosionStartDay
        EsmaClearingObligationFlag
        EsmaFinalPriceType
        EsmaNotionalCurrency1Id
        EsmaTransactionType
        EtfPriceType
        ExchangeCode
        ExchangeMarketSize
        ExerciseBeginDate
        ExerciseEndDate
        ExpiryDateEsma
        ExplicitCoraxVersionNumber
        FinalInventoryDay
        FinancialInstrumentShortNamesEsma {
          FinInstrShortNameEsma
          LanguageId
        }
        FirstBlockTASDay
        FirstDeliveryDay
        FirstIntentionDay
        FirstTradingDate
        FreightSubTypeSizeEsma
        FurtherSubProduct
        FurtherSubProductEsma
        HkasKCASEligible
        HkvcmEligible
        InitialInventoryDueDay
        InitialMargin {
          InitialMargin
        }
        IrishStampDutyPayable
        IssuePrice
        LastBlockTASDay
        LastDeliveryDay
        LastEfpDay
        LastIntentionDay
        LastTradingDate
        ListMarket
        LotSize
        LseOpol
        MaintenanceMargin {
          MaintenanceMargin
        }
        MethodOfDelivery
        Mic
        MifidContractType
        MifidFinalPriceType
        MifidTransactionType
        NoticeDayFirst
        NoticeDayLast
        OptionExerciseStyle
        OptionStub
        OptionStyle
        OptionTypeEsma
        OriginalExpiryDate
        PanelOfTakeoversAndMergersLevyEligible
        PaymentDate
        PercentofTUWin12MTR
        PositionRemovalDay
        PriceMultiplierEsma
        PricingGroupCode
        PricingGroupName
        PricingUnit
        PrimaryQuoteFlag
        PrimaryTradableMarketQuote
        QuoteAdminStatus {
          QuoteAdminStatus
          QuoteAdminStatusAdminStatusReason
          QuoteAdminStatusEffectiveFrom
        }
        QuoteAssetCategory
        QuoteAssetClassId
        QuoteAssetType
        QuoteCommonNames {
          LanguageId
          QuoteCommonName
        }
        QuoteCountryId
        QuoteCountryIdobjectTypeId
        QuoteCurrencyId
        QuoteExchangeCode
        QuoteExerciseStyle
        QuoteExpiryDate
        QuoteId
        QuoteIdObjectTypeId
        QuoteInstrumentId
        QuoteIsActive
        QuoteIsEventAdjusted
        QuoteLotSize
        QuoteLotUnit
        QuoteRcsAssetClass
        QuoteType
        RateType
        RealTimeExchangeCode
        RegulationShoStatusFlag
        RequestforAdmissionToTradingByIssuerEsma
        RetireDate
        RoundLotSize
        RouteTimeCharterAverageEsma
        Rule144ARegistered
        Rule4320StatusFlag
        SearchDisplayNames {
          LanguageId
        }
        SearchRanking
        SeriesDescriptions {
          LanguageId
          SeriesDescription
        }
        SettlementCurrencyId
        SettlementDay
        SettlementPeriod
        ShareClass
        ShortNames {
          QuoteShortName
          QuoteShortNameLanguageId
        }
        ShortSellRestrictionType
        StalenessIndicator
        StampDuty
        StrikePrice
        StrikePriceEsma
        StrikePriceMultiplier
        SubProduct
        SubProductEsma
        SuspendedFlag
        TenorType
        TenorValue
        TerminationDateEsma
        TickSize
        TickSizePilotGroup
        TickValue
        TickValueCurrencyId
        TisUpdateFrequency
        TradingGroup
        TradingMarket
        TradingObligationEsma
        TradingParameterCode
        TradingStatus
        UKStampDutyPayable
        UnderlyingCommodityId
        UnderlyingCommodityIdObjectTypeId
        UnderlyingIndexNameEsmaQuote
        UnderlyingIndexNames {
          LanguageId
          UnderlyingIndexName
        }
        UnderlyingIndexNamesEsma {
          LanguageId
        }
        UnderlyingTypeEsma
        UnscaledStrikePrice
        UnsolicitedOnlyFlag
        WarrantIssueDate
        WhenDistributedQuoteFlag
        WhenIssued
      }
      QuoteIdentifiers {
        IdentifierTypeId
        IdentifierData {
          IdentifierEffectiveFrom
          IdentifierValue
          PrimaryIdentifierFlag
        }
      }
    }
  }
}