#Organization query that accepts a list of Organization PermIDs and returns 
#all Organization Reference data attributes and relationships.

query OrganizationReference($ObjectList: [String!], $DeltaDate:DateTime!) {
  OrganizationReference(objectIds: $ObjectList, delta:{from:$DeltaDate}) {
    ObjectId
    Names {
      Name {
        OrganizationName {
          EffectiveFromDate
          EffectiveFromNACode
          EffectiveToDate
          EffectiveToNACode
          LanguageId
          LastModifiedDate
          Name
          NameTypeCode
          NormalizedName
          PrimaryNameFlag
          ProviderId
          ProviderType
          SequenceNumber
          SourceLink
          SourceType
          SourceUpdateDate
          TransliteratedName
        }
      }
    }
    Addresses {
      AddressLastModifiedDate
      AddressSourceLink
      AddressTypeCode
      City
      CountryId
      EffectiveFrom
      LanguageId
      Line1
      Line1Transliterated
      Line2
      Line2Transliterated
      Line3
      Line3Transliterated
      OrganizationId
      PostalCode
      SourceTypeCode
      SourceUpdateDate
      StateProvinceId
      StateProvinceOfficialCode
    }
    AddressReview {
      OrganizationCreatedDate
      OrganizationId
      OrganizationLastReviewDate
      OrganizationModifiedDate
    }
    Business {
      BusinessCreatedDate
      BusinessLastReviewedDate
      BusinessModifiedDate
      Description {
        BusinessDescription
        BusinessDescriptionEffectiveFrom
        BusinessDescriptionLanguageId
        BusinessDescriptionLastModified
        Provenance {
          SourceFilingDate
          SourceLanguageId
          SourceLink
          SourceTypeCode
          SourceUpdateDate
        }
      }
    }
    ClassificationNaceSectorIdV2
    ClassificationNaicsPrimaryIdV2
    #ClassificationNaicsSecondaryIdV2
    ClassificationTrbcPrimaryIdV2
    #ClassificationTrbcSecondaryIdV2
    OrganizationIdentifiers {
      IdentifierTypeId
      IdentifierData {
        Identifier
        IdentifierCreatedDate
        IdentifierEffectiveFrom
        LastModifiedDate
        Source
        SourceLastUpdateDate
        SourceTypeCode
        SourceUpdateDate
      }
    }
    OrganizationPhone {
      OrganizationPhoneFaxEffectiveFrom
      OrganizationPhoneFaxLastModified
      OrganizationPhoneFaxNumber
      OrganizationPhoneFaxSourceLink
      OrganizationPhoneFaxType
      SourceTypeCode
      SourceUpdateDate
    }
    Details {
      OrganizationDetails {
        AdminStatus
        AdminStatusEffectiveFrom
        AdminStatusEffectiveFromNACode
        AdminStatusEffectiveTo
        AdminStatusEffectiveToNACode
        AdminStatusLastModified
        AdminStatusReason
        CreatedDate
        FoundedDay
        FoundedDayProviderId
        FoundedDayProviderType
        FoundedDaySourceLink
        FoundedDaySourceTypeCode
        FoundedDaySourceUpdateDate
        FoundedMonth
        FoundedMonthProviderId
        FoundedMonthProviderType
        FoundedMonthSourceLink
        FoundedMonthSourceTypeCode
        FoundedMonthSourceUpdateDate
        FoundedYear
        FoundedYearNACode
        FoundedYearProviderId
        FoundedYearProviderType
        FoundedYearSourceLink
        FoundedYearSourceTypeCode
        FoundedYearSourceUpdateDate
        InactiveDay
        InactiveDayProviderId
        InactiveDayProviderType
        InactiveDaySourceLink
        InactiveDaySourceTypeCode
        InactiveDaySourceUpdateDate
        InactiveEventTypeCodeProviderId
        InactiveEventTypeCodeProviderType
        InactiveEventTypeCodeSourceLink
        InactiveEventTypeCodeSourceTypeCode
        InactiveEventTypeCodeSourceUpdateDate
        InactiveMonth
        InactiveMonthProviderId
        InactiveMonthProviderType
        InactiveMonthSourceLink
        InactiveMonthSourceTypeCode
        InactiveMonthSourceUpdateDate
        InactiveReasonCode
        InactiveYear
        InactiveYearProviderId
        InactiveYearProviderType
        InactiveYearSourceLink
        InactiveYearSourceTypeCode
        InactiveYearSourceUpdateDate
        IpoDate
        IpoDateProviderId
        IpoDateProviderType
        IpoDateSourceLink
        IpoDateSourceTypeCode
        IpoDateSourceUpdateDate
        JurisdictionOfIncEffectiveFromNACode
        JurisdictionOfIncorporation
        JurisdictionOfIncorporationEffectiveFrom
        JurisdictionOfIncorporationEffectiveTo
        JurisdictionOfIncorporationLastModified
        JurisdictionOfIncorporationNACode
        JurisdictionOfIncorporationProviderId
        JurisdictionOfIncorporationProviderType
        JurisdictionOfIncorporationSourceLink
        JurisdictionOfIncorporationSourceTypeCode
        JurisdictionOfIncorporationSourceUpdateDate
        LastReviewedDate
        LicensedOrganizationCompleteness
        ModifiedDate
        ObjectTypeId
        OrganizationCreatedBy
        OrganizationManagedFlag
        OrganizationManagedFlagEffectiveFrom
        OrganizationManagedFlagEffectiveFromNACode
        OrganizationManagedFlagEffectiveTo
        OrganizationManagedFlagEffectiveToNACode
        OrganizationManagedFlagLastModified
        OrganizationManagedFlagProviderId
        OrganizationManagedFlagProviderType
        OrganizationManagedFlagSourceLink
        OrganizationManagedFlagSourceTypeCode
        OrganizationManagedFlagSourceUpdateDate
        OrganizationProviderTypeCode
        OrganizationProviderTypeCodeEffectiveFrom
        OrganizationProviderTypeCodeEffectiveFromNACode
        OrganizationProviderTypeCodeEffectiveTo
        OrganizationProviderTypeCodeEffectiveToNACode
        OrganizationProviderTypeCodeLastModified
        OrganizationProviderTypeCodeProviderId
        OrganizationProviderTypeCodeProviderType
        OrganizationProviderTypeCodeSourceLink
        OrganizationProviderTypeCodeSourceTypeCode
        OrganizationProviderTypeCodeSourceUpdateDate
        OrganizationStatusCode
        OrganizationSubTypeCode
        OrganizationTier
        OrganizationTierEffectiveFrom
        OrganizationTierEffectiveFromNACode
        OrganizationTierEffectiveTo
        OrganizationTierEffectiveToNACode
        OrganizationTierLastModified
        OrganizationTierProviderId
        OrganizationTierProviderType
        OrganizationTierSourceLink
        OrganizationTierSourceTypeCode
        OrganizationTierSourceUpdateDate
        OrganizationTypeCode
        OrganizationVerifiedFlag
        OrganizationVerifiedFlagEffectiveFrom
        OrganizationVerifiedFlagEffectiveFromNACode
        OrganizationVerifiedFlagEffectiveTo
        OrganizationVerifiedFlagEffectiveToNACode
        OrganizationVerifiedFlagLastModified
        OrganizationVerifiedFlagProviderId
        OrganizationVerifiedFlagProviderType
        OrganizationVerifiedFlagSourceLink
        OrganizationVerifiedFlagSourceTypeCode
        OrganizationVerifiedFlagSourceUpdateDate
        OrganizationWebSiteLanguageId
        OrganizationWebsite
        ProviderStatus
        ProviderStatusEffectiveFrom
        ProviderStatusEffectiveFromNACode
        ProviderStatusEffectiveTo
        ProviderStatusEffectiveToNACode
        ProviderStatusLastModified
        ProviderStatusReason
        PublicFlag
        PublicFlagEffectiveFrom
        PublicFlagEffectiveFromNACode
        PublicFlagEffectiveTo
        PublicFlagEffectiveToNACode
        PublicFlagProviderId
        PublicFlagProviderType
        PublicFlagSourceLink
        PublicFlagSourceTypeCode
        PublicFlagSourceUpdateDate
        PublicLastModified
        SmeFlag
        SmeFlagProviderId
        SmeFlagProviderType
        SmeFlagSourceLink
        SmeFlagSourceTypeCode
        SmeFlagSourceUpdateDate
        StatusCodeEffectiveFrom
        StatusCodeEffectiveFromNACode
        StatusCodeEffectiveTo
        StatusCodeEffectiveToNACode
        StatusCodeLastModified
        StatusCodeProviderId
        StatusCodeProviderType
        StatusCodeSourceLink
        StatusCodeSourceTypeCode
        StatusCodeSourceUpdateDate
        SubtypeCodeEffectiveFrom
        SubtypeCodeEffectiveFromNACode
        SubtypeCodeEffectiveTo
        SubtypeCodeEffectiveToNACode
        SubtypeCodeLastModified
        SubtypeCodeProviderId
        SubtypeCodeProviderType
        SubtypeCodeSourceLink
        SubtypeCodeSourceTypeCode
        SubtypeCodeSourceUpdateDate
        Subunit
        SubunitEffectiveFrom
        SubunitEffectiveFromNACode
        SubunitEffectiveTo
        SubunitEffectiveToNACode
        SubunitIsPrimary
        SubunitLastModified
        TypeCodeEffectiveFrom
        TypeCodeEffectiveFromNACode
        TypeCodeEffectiveTo
        TypeCodeEffectiveToNACode
        TypeCodeLastModified
        TypeCodeProviderId
        TypeCodeProviderType
        TypeCodeSourceLink
        TypeCodeSourceTypeCode
        TypeCodeSourceUpdateDate
        WebsiteLastModified
        WebsiteNACode
        WebsiteProviderId
        WebsiteProviderType
        WebsiteSourceLink
        WebsiteSourceTypeCode
        WebsiteSourceUpdateDate
      }
      OrgDetailsHist {
        Id
        ObjectTypeId
        StatusCode
        StatusCodeEffectiveFrom
        StatusCodeEffectiveFromNACode
        StatusCodeEffectiveTo
        StatusCodeEffectiveToNACode
        StatusCodeLastModified
        StatusCodeProviderId
        StatusCodeProviderType
        StatusCodeSourceLink
        StatusCodeSourceType
        StatusCodeSourceUpdateDate
        AdminStatus {
          AdminStatus
          AdminStatusEffectiveFrom
          AdminStatusEffectiveFromNACode
          AdminStatusEffectiveTo
          AdminStatusEffectiveToNACode
          AdminStatusLastModified
          AdminStatusReason
        }
        IsManaged {
          IsOrgManaged
          IsOrgManagedEffectiveFrom
          IsOrgManagedEffectiveFromNACode
          IsOrgManagedEffectiveTo
          IsOrgManagedEffectiveToNACode
          IsOrgManagedLastModified
          IsOrgManagedProviderId
          IsOrgManagedProviderType
          IsOrgManagedSourceLink
          IsOrgManagedSourceType
          IsOrgManagedSourceUpdateDate
        }
        IsPublic {
          IsPublic
          IsPublicEffectiveFrom
          IsPublicEffectiveFromNACode
          IsPublicEffectiveTo
          IsPublicEffectiveToNACode
          IsPublicProviderId
          IsPublicProviderType
          IsPublicSourceLink
          IsPublicSourceType
          IsPublicSourceUpdateDate
          PublicLastModified
        }
        IsVerified {
          IsOrgVerified
          IsOrgVerifiedEffectiveFrom
          IsOrgVerifiedEffectiveFromNACode
          IsOrgVerifiedEffectiveTo
          IsOrgVerifiedEffectiveToNACode
          IsOrgVerifiedLastModified
          IsOrgVerifiedProviderId
          IsOrgVerifiedProviderType
          IsOrgVerifiedSourceLink
          IsOrgVerifiedSourceType
          IsOrgVerifiedSourceUpdateDate
        }
        OrganizationTier {
          OrgTier
          OrgTierEffectiveFrom
          OrgTierEffectiveFromNACode
          OrgTierEffectiveTo
          OrgTierEffectiveToNACode
          OrgTierLastModified
          OrgTierProviderId
          OrgTierProviderType
          OrgTierSourceLink
          OrgTierSourceType
          OrgTierSourceUpdateDate
        }
        ProviderStatus {
          ProviderStatus
          ProviderStatusEffectiveFrom
          ProviderStatusEffectiveFromNACode
          ProviderStatusEffectiveTo
          ProviderStatusEffectiveToNACode
          ProviderStatusLastModified
          ProviderStatusReason
        }
        ProviderTypeCode {
          OrgProviderTypeCode
          OrgProviderTypeCodeEffectiveFrom
          OrgProviderTypeCodeEffectiveFromNACode
          OrgProviderTypeCodeEffectiveTo
          OrgProviderTypeCodeEffectiveToNACode
          OrgProviderTypeCodeLastModified
          OrgProviderTypeCodeProviderId
          OrgProviderTypeCodeProviderType
          OrgProviderTypeCodeSourceLink
          OrgProviderTypeCodeSourceType
          OrgProviderTypeCodeSourceUpdateDate
        }
        SubtypeCode {
          SubtypeCode
          SubtypeCodeEffectiveFrom
          SubtypeCodeEffectiveFromNACode
          SubtypeCodeEffectiveTo
          SubtypeCodeEffectiveToNACode
          SubtypeCodeLastModified
          SubtypeCodeProviderId
          SubtypeCodeProviderType
          SubtypeCodeSourceLink
          SubtypeCodeSourceType
          SubtypeCodeSourceUpdateDate
        }
        TypeCode {
          TypeCode
          TypeCodeEffectiveFrom
          TypeCodeEffectiveFromNACode
          TypeCodeEffectiveTo
          TypeCodeEffectiveToNACode
          TypeCodeLastModified
          TypeCodeProviderId
          TypeCodeProviderType
          TypeCodeSourceLink
          TypeCodeSourceType
          TypeCodeSourceUpdateDate
        }
      }
      OrganizationRatings {
        CurrentRating {
          EffectiveFromDate
          EffectiveToDate
          OrganizationId
          OrganizationRating
          OrganizationRatingEndorsementCode
          OrganizationRatingSourceCode
          PreliminaryFlag
          RatingAgencyBranchLei
          RatingAgencyEndorsedLei
          ScopeCode
          UnsolicitedFlag
          VerifiedDate
        }
      }
    }
    AcquiredBy {
      ObjectId
    }
    AffiliatedOrganization {
      ObjectId
    }
    MergedWith {
      ObjectId
    }
    Parent {
      ObjectId
    }
    PrimaryRegulator {
      ObjectId
    }
    RegistrationAuthority {
      ObjectId
    }
    Subsidiaries {
      ObjectId
    }
    SucceededBy {
      ObjectId
    }
    TaxAuthority {
      ObjectId
    }
    UltimateParent {
      ObjectId
    }
    UltimateParentOf {
      ObjectId
    }
  }
}