#GovCorp Instrument, AllQuote querty
#This query takes Instrument PermIDs from the InstrumentList query variable and requests
#all content items and relationships
query InstrumentRefData($ObjectList: [String!]) {
  GovCorpInstrument(objectIds: $ObjectList) {
    ObjectId
    Reference {
      AaoifiCompliantFlag
      AnnouncementDate
      AnnuityFlag
      AssetCharacteristicsCode
      AssetDuplicationCode
      AssetSetupDate
      AssetSubTypeCode
      BabyBondFlag
      BondSubTypeCode
      CallableFlag
      CallableNotationText
      CapitalContingentDebtFlag
      CapitalTierCode
      CapitalizationFlag
      CdcAssetClassCode
      Cfi
      Cic
      ClawbackTypeCode
      CleanUpCallFlag
      ConvertibleFlag
      ConvertibleIssueTypeCode
      CouponCapRate
      CouponFloorRate
      CouponTypeCode
      CreditSensitiveFlag
      CrrCompliantFlag
      CurrentInterestDeferredFlag
      DataCalculationServicesCode
      DefeasableFlag
      DeferredInterestConversionDate
      DenominationIncrementAmount
      DenominationTypeCode
      DistributionSourceCode
      DividendPusherFlag
      DividendStopperFlag
      DomesticCalendarSettleCode
      DomesticSettlementValue
      DrdEligibleFlag
      DtcEligibleFlag
      DualCurrencyFlag
      EmergingMarketFlag
      EquityClawBackFlag
      EsgBondFlag
      EstimatedFreeConversionFlag
      EusdTaxFlag
      EvaluatedPriceRic
      ExDividendCalendarCode
      ExDividendValue
      ExchangeListedFlag
      ExpectedMaturityDate
      ExpectedReturnScore
      ExtendibleMaturityFlag
      FacilityAmount
      FacilityIdentifierValue
      FdicInsuredFlag
      FigureRuleCode
      FinancialInstrumentShortName
      FinraTraceEligibleCode
      FinraTradeGradeCode
      FirstCouponDate
      FlipOptionCode
      FlipOptionDate
      FlipOptionFlag
      FttLiableBondFlag
      FttReportingEligibleBondFlag
      FungibleFlag
      GreenBondFlag
      GuaranteedFlag
      HolidayConventionForSettlementCode
      HybridFlag
      InflationProtectionFlag
      InitialPhysicalFormCode
      InstrumentClassification
      InstrumentId
      InstrumentName
      IsaEligibleFlag
      IssueCurrencyIsoCode
      IssuedAmount
      LastCouponBeforeMaturityDate
      LetterOfCreditFlag
      LiquidationPreferenceCode
      LocalIssueDate
      MakeWholeCallFlag
      MaturityDate
      MinimumDenominationAmount
      MoodysDebtClassCode
      MrelEligibleFlag
      MultiStepFloatFlag
      NextCallDate
      NextCallPrice
      NextPutDate
      NextPutPrice
      NextResetDate
      OddFirstCoupon
      OddFirstCouponCode
      OddFirstCouponFlag
      OddLastCouponCode
      OddLastCouponFlag
      OriginalIssueDate
      OriginalIssueDiscountFlag
      OverSubscriptionPercent
      PaymentInKindFlag
      PaymentInPartFlag
      PreferredRic
      PrimaryCountryOfIssueIsoCode
      PrincipalAdjustedFlag
      PrivatePlacementFlag
      ProgramIssuedFlag
      ProjectName
      ProspectusOnFileFlag
      PutableFlag
      PuttableNotationText
      QdiEligibleFlag
      RecordDateCode
      RecordDateValue
      RecourseToIssuerCode
      RedemptionValue
      RetailSecurityFlag
      RiskClassificationsCode
      RiskCountryIsoCode
      SecurityClassCode
      SecurityCode
      SecurityDescription
      SecurityDescriptionSupplementaryText
      SecuritySourceCode
      SeniorityCode
      SeriesName
      SinkingAmortizationFlag
      SolvabilityRatio
      SpecialPutFlag
      StandardAndPoorsDebtClassCode
      StatusOfDocumentCode
      StraightBondFlag
      StrippableFlag
      StructuredSecurityCode
      StructuredSecurityFlag
      SurvivorOptionFlag
      TapEndDate
      TapIssueFlag
      TaxCallFlag
      TermToMaturityYears
      TlacEligibleFlag
      TogglePaymentInKindFlag
      TotalStripAmount
      TradeSettlementCurrencyIsoCode
      TradingFlag
      UcitsCompliantFlag
      UnitComponentCode
      WarrantsFlag
      WithholdingTaxRate
      WriteDownFlag
      WriteDownTriggerCode
      WriteDownTriggerRatio
      WriteDownTypeCode
      WriteUpFlag
    }
    Identifiers {
      EffectiveFromDate
      IdentifierCode
      IdentifierValue
      InstrumentId
    }
    AlternativeIdentifiers {
      IdentifierCode
      IdentifierValue
      InstrumentId
    }
    AccretionSchedule {
      AccrededValueAtStartDatePercent
      AccretedValueAtEndDatePercent
      AccretionEndDate
      AccretionLegNumber
      AccretionStartDate
      InstrumentId
    }
    AccretionTerms {
      AccretionMethodCode
      AccretionRate
      AccretionSequenceNumber
      InstrumentId
      InterestLegNumber
    }
    AdhocPayment {
      InstrumentId
      PaymentAmount
      PaymentCurrencyIsoCode
      PaymentDate
      PaymentIdentifierCode
      PaymentIdentifierValue
      PaymentReasonCode
      PaymentTypeCode
    }
    AmountHeldAllocation {
      AllocationDate
      CurrencyIsoCode
      InstrumentId
      OutstandingHeldByGovernmentAmount
      OutstandingHeldByMarketplaceAmount
      OutstandingHeldByOthersAmount
      OutstandingHeldNonAuctionedAmount
    }
    AmountOutstandingHistory {
      ChangeAmount
      CurrencyIsoCode
      EffectiveFromDate
      FaceValueFactor
      InstrumentId
      IssuePrice
      IssueYield
      NetChangeCode
      RecordDate
      SourceTypeCode
      TotalOutstandingAmount
    }
    AssetStatus {
      AssetStatusCode
      EffectiveFromDate
      EffectiveToDate
      InstrumentId
    }
    CallTerms {
      CallHolidayConventionCode
      CallLegNumber
      CallMakeWholeLegNumber
      CallMakeWholeSpreadRate
      CallMakeWholeTreasuryItem
      CallMaximumEquityClawbackAmount
      CallMethodCode
      CallNoticeDaysUnitCode
      CallOptionCode
      CallTermsTypeCode
      FinalCallPrice
      FrequencyCode
      InstrumentId
      MaximumCallNoticeDays
      MinimumCallNoticeDays
      PerpetualCallScheduleFlag
      SpecialCallTypeCode
    }
    CallSchedule {
      CallTypeCode
      EffectiveFromDate
      EffectiveToDate
      InstrumentId
      LegNumber
      Price
    }
    Classification {
      ClassificationCode
      ClassificationSchemeCode
      EffectiveFromDate
      InstrumentId
    }
    ClassificationSchemeProperties {
      InstrumentId
      PropertyCode
    }
    ComplexInstrumentType {
      ComplexInstrumentCode
      InstrumentId
    }
    ConvertibleCallSchedule {
      AccretionMethodCode
      AccretionRate
      CallEndPrice
      CallTypeCode
      ForcedConversionRatio
      InstrumentId
      LegNumber
      Price
      RedemptionBeginDate
      RedemptionEndDate
    }
    ConvertibleCoco {
      CapitalContingentConversion
      CocoComment
      ConvertiblePremiumLevelTriggerValue
      DebtTriggerRatio
      EffectiveFromDate
      EquityConversionOffsetNumber
      EquityResetPeriod
      EquityResetTypeCode
      EquityTriggerCode
      EquityTriggerIncrementAmount
      EquityTriggerKnockInFlag
      EquityTriggerOutOfDays
      EquityTriggerSamplePeriod
      EquityTriggerValue
      InstrumentId
      LegNumber
      MultipleRatingTriggerLogicCode
      Period
      PremiumTriggerConvertibleForPeriod
      PremiumTriggerGracePeriod
      PremiumTriggerOutOfDays
      PremiumTriggerSampleDays
      ResetYearTypeCode
      Trigger1AgencyCode
      Trigger1Rating
      Trigger2AgencyCode
      Trigger2Rating
      Trigger3AgencyCode
      Trigger3Rating
      TriggerOffsetValue
    }
    ConvertibleComplexRedemption {
      InstrumentId
      MaximumNoticePeriod
      MinimumNoticePeriod
      NoticePeriodDaysCode
      PaymentCalculationTypeCode
      PaymentComponentsTypeCode
      PriceAveragingDays
      PriceDelayDays
      PriceDelayDaysCode
      RedemptionFactor
      RedemptionPriceCode
      RedemptionTypeCode
    }
    ConvertibleCopayPayoff {
      EndDate
      HighMaximumPayment
      HighMinimumPayment
      HighPayPercent
      InstrumentId
      LegNumber
      LowMaximumPayment
      LowMinimumPayment
      LowPayPercent
      PayPercentageUnitCode
      StartDate
    }
    ConvertibleCopayTrigger {
      EndDate
      HighTriggerChangeRate
      HighTriggerCode
      HighTriggerConditionCode
      HighTriggerMaximumPercent
      HighTriggerMinimumPercent
      HighTriggerPercent
      InstrumentId
      LegNumber
      LowTriggerChangeRate
      LowTriggerCode
      LowTriggerConditionCode
      LowTriggerMaximumPercent
      LowTriggerMinimumPercent
      LowTriggerPercent
      PaymentCombinationCode
      PaymentFrequencyCode
      StartDate
      TriggerDays
      TriggerEndDays
      TriggerPriceCalculationCode
      TriggerPriceCode
      TriggerReferencePriceCode
    }
    ConvertibleDefinition {
      ConvertibleIssueStatusCode
      ConvertibleMajorTypeCode
      ConvertiblePricingDate
      ConvertibleSubTypeCode
      ConvertibleTrancheTypeCode
      CrossCurrencyFlag
      EffectiveFromDate
      InstrumentId
      InvertedFXRateFlag
      IssueSizeEURAmount
      IssueSizeUSDAmount
      MaceIssueIdentifierValue
      MandatoryConversionFlag
      NonFaceSettlementCurrencyIsoCode
      NonFaceSettlementCurrencyOptionTypeCode
      SecondaryTrancheFlag
      SharesDeliveryCode
      UnderlyingAssetCurrencyIsoCode
      UnderlyingAssetDomicileIsoCode
      UnderlyingAssetRic
    }
    ConvertibleDividendProtection {
      CalculationMethodCode
      CashThreshholdCorrectedAmount
      CashThresholdAmount
      CompensationMethodCode
      DividendProtectionAccumulationTypeCode
      DividendProtectionDescription
      DividendProtectionDirectionCode
      DividendProtectionQualifyingDividendCode
      DividendProtectionScaleFactor
      DividendProtectionStockPriceDays
      DividendProtectionStockPriceEndDateCode
      DividendProtectionStockPriceEndDays
      DividendProtectionStockPriceMethodCode
      EarningsThresholdPercent
      InstrumentId
      LogicThresholdCode
      MinimumChangeAmount
      MinimumChargeAmount
      ThresholdEndDate
      ThresholdPeriodCode
      ThresholdPreviousDividendPercent
      ThresholdStartDate
      ThresholdYield
    }
    ConvertibleHurdle {
      ConvertibleTermsLegNumber
      EffectiveFromDate
      EffectiveToDate
      HurdleAllocationMethodCode
      HurdleCurrencyIsoCode
      HurdleDayCode
      HurdleDayValue
      HurdleDurationCode
      HurdleDurationValue
      HurdleLegNumber
      HurdleNoticeCode
      HurdleNoticeValue
      HurdlePriceCode
      HurdleRedemptionCode
      HurdleRedemptionEndPrice
      HurdleRedemptionPrice
      HurdleTypeCode
      HurdleTypePrice
      InstrumentId
      MakeWholeLegNumber
      RedemptionPriceAccretionMethodCode
      RedemptionPriceAccretionRate
    }
    ConvertibleInstrumentFeature {
      EffectiveFromDate
      FeatureEndDate
      InstrumentFeatureCode
      InstrumentId
    }
    ConvertibleIssueRange {
      InstrumentId
      RangeMaximumValue
      RangeMinimumValue
      RangeTermsSubjectCode
    }
    ConvertibleMakeWhole {
      CalculationTypeCode
      CashAmount
      CashDecrementAmount
      CashPaymentFactor
      DecrementFrequencyCode
      FinalCouponDate
      FirstDecrementDate
      InstrumentId
      MakeWholeCap
      MakeWholeDays
      MakeWholeDaysCode
      MakeWholeEndDate
      MakeWholeFloor
      MakeWholeLegNumber
      MakeWholePriceCode
      MakeWholeStartDate
      MakeWholeTypeCode
      PaymentTypeCode
      PresentVValueRateSourceCode
      PresentValueRate
      PresentValueTypeCode
      ShareSettlementFactor
    }
    ConvertibleRefix {
      ConvertibleTermsLegNumber
      EffectiveFromDate
      InstrumentId
      RefixCapPercent
      RefixDays
      RefixDaysCode
      RefixFloorPercent
      RefixHurdleCurrencyIsoCode
      RefixHurdleLowerPrice
      RefixHurdleUpperPrice
      RefixPremiumPercent
      RefixReferencePrice
      RefixSettingDate
      RefixTypeCode
    }
    ConvertibleSchedule {
      CashPaymentAmount
      CashPaymentCurrencyIsoCode
      ConversionCurrencyIsoCode
      ConversionFormulaText
      ConversionParValue
      ConversionPrice
      ConversionRatio
      EffectiveFromDate
      EstimatedTermsFlag
      EventDescriptionCode
      FXRate
      ForexRateCode
      FractionalPaymentAmount
      FractionalPaymentCurrencyIsoCode
      InstrumentId
      LegNumber
    }
    ConvertibleTerms {
      CoCoLegNumber
      ConversionStructureType
      ConvertibleOptionCode
      ConvertibleOptionFrequencyCode
      ConvertibleTermsLegNumber
      ConvertibleTypeCode
      DBSConversionTermsIdentifierValue
      DilutionProtectionCode
      EffectiveFromDate
      EffectiveToDate
      ExchangeableDebtCode
      ExerciseCode
      FractionsCode
      InstrumentId
      InterestCode
      MakeWholeLegNumber
      NoticePeriodCode
      NoticePeriodValue
      PremiumAtIssuePercent
      SettlementCode
      SettlementPeriodCode
      SettlementPeriodValue
      StockBuybackCode
    }
    ConvertibleUnderlying {
      BasketWeightCode
      BasketWeightValue
      ConvertibleIssuerChoosesDeliveryFlag
      ConvertiblePriceRangeLower
      ConvertiblePriceRangeUpper
      ConvertibleRatioRangeLower
      ConvertibleRatioRangeUpper
      EffectiveFromDate
      InstrumentId
      KnockInEffectiveDate
      KnockInLevelCode
      KnockInLevelPrice
      KnockInPeriodEndDate
      KnockInReferenceCurrencyIsoCode
      KnockInReferencePrice
      KnocklInLevelCurrencyIsoCode
      LegNumber
      UnderlyingCurrencyIsoCode
      UnderlyingId
    }
    ConvertibleUnrealized {
      ConvertibleLegNumber
      InstrumentId
      UnderlyingIdentifier
      UnrealizedChangePercent
      UnrealizedConversionPrice
      UnrealizedConversionRatio
      UnrealizedEffectiveFromDate
    }
    CouponRateSchedule {
      CouponDeterminationDate
      CouponRate
      CouponRateCode
      EffectiveFromDate
      InstrumentId
      InterestLegNumber
      LastChangedDate
      NonAnnualCouponRate
      SourceCode
      UnadjustedResetDate
    }
    Covenants {
      AffiliateTransactionsFlag
      ChangeOfControlFlag
      ChangeOfControlPrice
      ChangeOfControlPutFlag
      ChangeOfControlPutPrice
      CollectiveActionClausesFlag
      CrossDefaultFlag
      DebtIncurrenceLimitationFlag
      DefaultEventsFlag
      FixedChargeCoverageFlag
      ForceMajeureClauseCode
      ForceMajeureFlag
      InstrumentId
      KeepwellAgreementFlag
      LimitationOnLiensFlag
      MergerFlag
      NegativePledgeFlag
      NetWorthMaintenanceFlag
      OtherCovenantFlag
      PariPassuFlag
      PayRestrictionsSubsidiaryFlag
      RestrictedPaymentFlag
      RestrictiveFinancialCovenantFlag
      SaleLeasebackFlag
      SaleOfAssetsFlag
      SpecialClauseFlag
      SubordinationFlag
    }
    CreditSensitiveTerms {
      ComplexFlag
      CreditSensitivePerRatingFlag
      InstrumentId
      NoLongerCreditSensitiveFlag
      NonCreditSensitivityEffectiveFromDate
      RateEffectivePeriodTypeCode
      RatingWithdrawalPercent
    }
    CreditSensitiveDefinition {
      InstrumentId
      LegNumber
      PermanentNonCreditSensitivityFlag
      PutFlag
      RateIncreasePercent
      RatingAgencySourceCode
      RatingLowerThresholdCode
      RatingUpperThresholdCode
    }
    CreditSensitiveTerms {
      ComplexFlag
      CreditSensitivePerRatingFlag
      InstrumentId
      NoLongerCreditSensitiveFlag
      NonCreditSensitivityEffectiveFromDate
      RateEffectivePeriodTypeCode
      RatingWithdrawalPercent
    }
    Denomination {
      CurrencyCodeIsoCode
      DenominationAmount
      EffectiveFromDate
      EffectiveToDate
      InstrumentId
      InvestorCountryIsoCode
      MinimumDenominationAtIssuanceFlag
      MinimumDenominationFlag
    }
    EmuHarmonization {
      DayCountChangeDate
      HolidayChangeDate
      InstrumentId
      QuotationChangeDate
      SettlementChangeDate
    }
    EmuRedenomination {
      GoverningCountryIsoCode
      InstrumentId
      OddLotProcedureCode
      ReconciliationCode
      RedenominationConversionCode
      RedenominationDate
      RedenominationNotificationPeriod
      RedenominationRenominalizeCode
      RedenominationRoundingCode
      RedenominationStatusCode
      RedenominationTargetDate
    }
    Enhancements {
      CrossDefaultGuarantorFlag
      EffectiveFromDate
      EffectiveToDate
      EscrowAccountFlag
      EventsOfDefaultForGuarantorFlag
      GuaranteeTypeCode
      GuarantorOrganizationId
      GuarantorTypeProgramCode
      InstrumentId
      InterestCollateralTypeCode
      InterestCollateralizedPercent
      LegNumber
      LetterOfCreditExpirationDate
      NegativePledgeForGuarantorFlag
      OtherCovenantsForGuarantorFlag
      PrincipalCollateralTypeCode
      PrincipalCollateralizedPercent
    }
    ExDividendSchedule {
      ExDividendDate
      InstrumentId
      NextCouponCutOffDate
    }
    Exchanges {
      EffectiveDelistingDate
      EffectiveListingDate
      ExchangeCode
      InstrumentId
      MinimunTradingLotSize
      PrimaryListingFlag
    }
    ExtendibleSchedule {
      EffectiveFromDate
      ExtendPrice
      InstrumentId
    }
    ExtentibleTerms {
      EffectiveFromDate
      ExtendibleFrequenceCode
      ExtensionTermsEffectiveEndDate
      HolderOptionFlag
      InstrumentId
      MaximumNoticeDays
      MinimumNoticeDays
      PeriodUnitCode
    }
    FactorHistory {
      EffectiveFromDate
      IndexationFactor
      InstrumentId
      LegNumber
    }
    FlipTerms {
      FlipMaximumNoticePeriod
      FlipMinimumNoticePeriod
      FrequencyCode
      InstrumentId
      LegNumber
      MethodCode
      OptionCode
      PeriodUnitCode
      SpecialFlipCode
    }
    FlipSchedule {
      FlipEndDate
      FlipStartDate
      FlipTypeCode
      InstrumentId
      LegNumber
    }
    FundSchedule {
      ConversionRatio
      FundAmount
      FundTypeCode
      InstrumentId
      LegNumber
      SinkingFundDate
      SinkingFundPrice
    }
    FundTerms {
      AdditionalPaymentApplicationCode
      AdditionalPaymentCode
      AdditionalPaymentPercent
      AmountUnitCode
      AnnualRetiredPercent
      ConversionRedemptionFlag
      FundPeriodUnitCode
      FundTypeCode
      FunnelFlag
      ImprovementCollateralFlag
      InstrumentId
      LegNumber
      MaintenanceFlag
      MaximumNoticeDays
      MinimumNoticeDays
      ObligationFrequencyCode
      PrimaryFundFlag
      PrincipalAllocationCode
      PropertyAdditionalFlag
      SecurityDepositedSinkingFundPaymentFlag
      SinkCode
      SinkingTypeCode
    }
    InsuranceLinkedSecurityPeril {
      InstrumentId
      PerilCode
      PerilLocationCode
    }
    InsuranceLinkedSecurityTerms {
      ExpectedLossPercent
      InstrumentId
      ProbabilityOfAttachmentPercent
      ProbabilityOfExhaustionPercent
      ReferenceRateText
      ReferenceSpreadRate
      SensitivityPercent
      TrancheName
      TriggerCode
    }
    InKindTerms {
      CapRate
      CashRate
      InkindCode
      InkindEffectiveFromDate
      InkindEffectiveToDate
      InstrumentId
      LegNumber
      PaymentInKindRate
    }
    InterestDefinition {
      AccrualCode
      AccrualFrequencyCode
      AccruedInterestRoundingCode
      AlternateInterestCurrencyIsoCode
      ComplexFloaterFlag
      ComplexInstrumentFlag
      ComplexReasonCode
      CompoundingFrequencyCode
      CompoundingPeriodCode
      ContingentCouponFlag
      CouponCalculationMethodCode
      CouponCapRate
      CouponClassCode
      CouponCurrencyIsoCode
      CouponDeferrableFlag
      CouponDualCurrencyExchangeCode
      CouponDualCurrencyExchangeRate
      CouponFloorRate
      CouponFormulaJsonText
      CouponPaymentCalendarCode
      CouponPaymentCalendarValue
      CouponPaymentFrequencyCode
      CouponPaymentRuleCode
      CouponRateRoundingCode
      CouponResetCalendarCode
      CouponResetCalendarValue
      CouponResetFrequencyCode
      CouponResetRuleCode
      CumulativeFlag
      CutOffBusinessDayConventionCode
      DayCountCode
      EffectiveFromDate
      HolidayConventionforCutOffCode
      IndexFallbackFlag
      IndexHolidayConventionCode
      InstrumentId
      InterestPaymentAdjustedFlag
      InterestProtectionFlag
      InterestRateFormulaMultiplierValue
      InterestRateFormulaSpreadRate
      LegNumber
      MaturityCutOffDays
      NumberOfCutOffDays
      PayDayCountFlag
      PaymentHolidayConventionCode
      PaymentProceedsRoundingCode
      PeriodicCapRate
      PeriodicFloorRate
      PeriodicFrequencyCode
      PostDeterminedFlag
      RateHolidayConventionCode
      ResettableFlag
      SimpleFirstFlag
      TradingDayCountCode
      ValueDateCode
    }
    IslamicFinance {
      AaoifiCompliantFlag
      InstrumentId
      OfficialFatwaTextFlag
      RiskClassificationCode
      RiskCountryIsoCode
      ShariaOpinionAvailableInProspectusFlag
      SukukStructureFlag
    }
    IssuanceDefinition {
      AcceptedAuctionRange
      AnnualEffectiveYield
      AuctionAnnouncementDate
      AuctionAverageBondEquivalentYield
      AuctionAverageDiscountYield
      AuctionBidToCoverRatio
      AuctionCentralBankBidsAcceptedAmount
      AuctionCentralBankBidsReceivedAmount
      AuctionForeignBidsAcceptedAmount
      AuctionForeignBidsReceivedAmount
      AuctionHighBondEquivalentYield
      AuctionHighDiscountYield
      AuctionLowBondEquivalentYield
      AuctionLowDiscountYield
      AuctionLowPriceYield
      AuctionMethodCode
      AuctionOtherBidsAcceptedAmount
      AuctionOtherBidsReceivedAmount
      AuctionPriceForAverageYield
      AuctionPriceForHighYield
      AuctionPricingDate
      AuctionTotalBidsReceivedAmount
      AuctionTotalCompetitiveBidsAcceptedAmount
      AuctionTotalCompetitiveBidsReceivedAmount
      AuctionTotalNonCompetitiveBidsAcceptedAmount
      AuctionTotalNonCompetitiveBidsReceivedAmount
      AuctionTypeCode
      AuctionWhenIssuedTypeCode
      BondGradeCode
      CashManagementBillFlag
      CharacterOfOfferingCode
      DatedDate
      DirectBidderBidsAcceptedAmount
      DirectBidderBidsReceivedAmount
      DiscountsandCommissionsPerDebtSecurityPercent
      DiscountsandCommissionsPerShareOrUnitAmount
      DutchAuctionFlag
      IndicativeAmount
      IndirectBidderBidsAcceptedAmount
      IndirectBidderBidsReceivedAmount
      InstrumentId
      IssuanceEndDate
      IssueAmount
      IssueCurrencyIsoCode
      IssueDate
      IssuePrice
      IssueSpreadRate
      IssueYield
      LegNumber
      ManagementAndUnderwritingFeesCombinedAmount
      ManagementFeePerDebtSecurityPercent
      MidSwapsSpreadRate
      NonFixedPriceIssueFlag
      NonUnderwrittenSecuritiesIncludedFlag
      OnlineIssueAmount
      PraecipiumAmount
      PricingSupplementDate
      PricingSupplementNumber
      PrimaryDealerBidAcceptedAmount
      PrimaryDealerCompetitiveBidsRecievedAmount
      PrimaryDealerNonCompetitiveBidsAcceptedAmount
      ProceedsToRegistrantPerDebtSecurityPercent
      ProceedsToRegistrantPerShareAmount
      ReallowanceConcessionDebtSecurityPercent
      ReallowanceConcessionPerShareAmount
      ReferenceSpreadRate
      RegistrantExpensesAmount
      ReofferPrice
      ReofferSpreadRate
      ReofferYield
      SellingConcessionPerDebtSecurityPercent
      SellingConcessionPerShareAmount
      TailYield
      TotalDiscountsAndCommissionsAmount
      TotalExpensesOfferingAmount
      TotalPriceToPublicAmount
      TotalProceedsToRegistrantAmount
      UnderwritingFeePerDebtSecurityPercent
    }
    MifidComplexReason {
      ComplexReasonCode
      InstrumentId
    }
    MifidTerms {
      BondTypeCode
      CofiaFlag
      ComplexFlag
      EeaFlag
      InstrumentId
      MifirIdentifierCode
      SeniorityCode
    }
    Note {
      InstrumentId
      LargeNoteText
      NoteEffectiveFromDate
      NoteText
      NoteTypeCode
    }
    OriginalIssueTerms {
      AbbreviatedName
      ComparedToOriginalIssueText
      EUJumboFlag
      EusdTappedFlag
      GovernmentDebtTypeCode
      InstrumentId
      InstrumentIssueYield
      InstrumentTypeCode
      InvestmentGradeAtIssueCode
      IssueSharePrice
      MoodysCreditSupportFlag
      OverAllotmentAmount
      OverAllotmentDays
      OverAllotmentSharesAmount
      OverAllotmentSharesSoldAmount
      ParValue
      PriceIncludesAccruedInterestFlag
      PriceQuoteBaseValue
      PriceQuoteConventionCode
      PriceQuoteMethodCode
      PriceQuoteRoundingCode
      ProgramTypeCode
      RemarketingDate
      RemarketingFlag
      SeasoningDate
      SeparatelyTransferableDate
      SimpleInterestFirstFlag
      StandardAndPoorsCreditSupportFlag
      SwissBondExemptFromEusdFlag
      TermToMaturityDays
      TotalSharesUnitsOfferedAmount
      ValueDateCode
    }
    PayemtInKindFor {
      CoIssuerOrganizationId
      ComissionAgentOrganizationId
      ConversionExchangeAgentOrganizationId
      CustodianOrganizationId
      EscrowAgentOrganizationId
      ExchangeAgentOrganizationId
      GoverningLawGeographyId
      InformationAgentOrganizationId
      InvestmentAdvisorOrganizationId
      IssuerOrganizationId
      KeepwellProviderOrganizationId
      ObjectId
      ObligorOrganizationId
      OfferRegistrantOrganizationId
      RemarketingAgentOrganizationId
      RiskDomicileGeographyId
      SelfPlacedOrganizationId
      SubordinationGoverningLawGeographyId
      SukukObligorOrganizationId
    }
    PreferredInstrument {
      AntiTakeoverProvisionFlag
      AuthorizedSharesAmount
      CumulativeDividendFlag
      CumulativeVotingPrivilegeFlag
      DiscriminationProvisionFlag
      DividendReinvestmentFlag
      FutureCashDividendFlag
      HolderReceiverFlag
      IndicatedAnnualizedDividendAmount
      InitialDividendRate
      InstrumentId
      LiquidationRightsFlag
      LiquidationValue
      ParValue
      ParticipatingSharesFlag
      PreemptiveRightFlag
      VotingPrivilegeFlag
    }
    PrincipalDefinition {
      AlternateCurrencyIsoCode
      BaseIndexDate
      BaseIndexValue
      BasePaymentAmount
      BasePaymentCurrencyIsoCode
      HolidayConventionforIndexationFactorCode
      IndexationFactorCalendarCode
      IndexationFactorCalendarValue
      IndexationFactorChangeFrequencyCode
      IndexationFactorRuleCode
      InstrumentId
      PriceAdjustmentFlag
      PrincipalAdjustmentMethodCode
      PrincipalDefinitionEffectiveFromDate
      PrincipalDualCurrencyExchangeCode
      PrincipalDualCurrencyExchangeRate
      PrincipalFormulaJsonText
      PrincipalLegNumber
      PrincipalMaximumValue
      PrincipalMinimumValue
      PrincipalProtectedFlag
    }
    PutTerms {
      FrequencyCode
      HolidayConventionCode
      InstrumentId
      LegNumber
      MaximumPutNoticeDays
      MethodCode
      MinimumPutNoticeDays
      NoticeDaysUnitsCode
      OptionCode
      PerpetualPutScheduleFlag
      TermsTypeCode
    }
    PutSchedule {
      EffectiveFromDate
      EffectiveToDate
      InstrumentId
      LegNumber
      Price
      ScheduleTypeCode
    }
    RangeCriteria {
      ComplexRangeFlag
      ConditionalCouponHolidayConventionCode
      ConditionalCouponInRangeRate
      ConditionalCouponNextDeterminationDate
      ConditionalCouponNextResetDate
      ConditionalCouponOutOfRangeRate
      ConditionalCouponResetCalendarCode
      ConditionalCouponResetCalendarValue
      ConditionalCouponResetFrequencyCode
      ConditionalCouponResetRuleCode
      ConditionalCouponUnadjustedResetDate
      FormulaInRangeId
      FormulaOutOfRangeId
      FullRecalculationFlag
      InRangeCouponFormula
      InRangeFormulaJsonText
      InstrumentId
      InterestLegNumber
      LastChangeDate
      LowerRangeCriteriaAmount
      LowerRangeCriteriaOperatorCode
      OutOfRangeCouponFormula
      OutOfRangeFormulaJsonText
      RangeIndexFormulaJsonText
      RangeInformationEffectiveFromDate
      RangeLegNumber
      UnderlyingRangeIndex
      UpperRangeCriteriaAmount
      UpperRangeCriteriaOperatorCode
    }
    RangeFormulaTerms {
      DeterminationDate
      EffectiveFromDate
      InstrumentId
      InterestLegNumber
      LastChangeDate
      RangeLegNumber
      RangeRate
      RangeTypeCode
      ResetDate
      UnadjustedResetDate
    }
    Ratchet {
      BaselineConversionRatio
      CurrencyCodeIsoCode
      EventLevelUnitCode
      EventValueUnitCode
      InstrumentId
      MaximumRatchetValue
      MaximumValueUnitCode
      MinimumRatchetValue
      MinimumValueUnitCode
      PoisonPutEndDate
      PoisonPutLevelAmount
      PoisonPutTypeCode
      RatchetTypeCode
    }
    RatchetCoefficientTerms {
      CoefficientTypeCode
      CoefficientValue
      InstrumentId
    }
    RatchetEvent {
      EventDate
      EventLevelAmout
      EventValue
      InstrumentId
    }
    Rating {
      EffectiveFromDate
      InstrumentId
      IssuePreliminaryRatingFlag
      IssueRating
      IssueRatingEndorsementCode
      IssueRatingSuffixCode
      IssueRatingUnsolicitedFlag
      IssueRatingVerifiedDate
      RatingAgencyBranchLei
      RatingAgencyEndorsedLei
      SourceCode
      SourceInformationCode
    }
    RatingOutlook {
      EffectiveFromDate
      EffectiveToDate
      InstrumentId
      OutlookCode
      SourceCode
    }
    RatingWatch {
      EffectiveFromDate
      EffectiveToDate
      InstrumentId
      SourceCode
      TrendCode
    }
    RedemptionTerms {
      AcceptancePriorityLevelValue
      AdvisorName
      AnnouncementDate
      CompletionDate
      ConsentPrice
      ContentTenderWithdrawalDate
      DealManagerName
      EarlyExpirationDate
      EarlySettlementDate
      ExchangeAgentName
      ExpirationDate
      InformationAgentName
      InstrumentId
      MarketReportSourceTypeCode
      MarketReportSubTypeCode
      MarketReportTypeCode
      RecordDate
      RedemptionAmount
      RedemptionDate
      RedemptionPrice
      RequiredForCompletionAmount
      SecurityBeingReceivedInExchangeText
      StatusCode
      TenderCapAmount
      TenderPercent
      TenderPremiumAmount
      TenderPrice
      TenderSettlementDate
    }
    RedenominatedFor {
      CoIssuerOrganizationId
      ComissionAgentOrganizationId
      ConversionExchangeAgentOrganizationId
      CustodianOrganizationId
      EscrowAgentOrganizationId
      ExchangeAgentOrganizationId
      GoverningLawGeographyId
      InformationAgentOrganizationId
      InvestmentAdvisorOrganizationId
      IssuerOrganizationId
      KeepwellProviderOrganizationId
      ObjectId
      ObligorOrganizationId
      OfferRegistrantOrganizationId
      RemarketingAgentOrganizationId
      RiskDomicileGeographyId
      SelfPlacedOrganizationId
      SubordinationGoverningLawGeographyId
      SukukObligorOrganizationId
    }
    RegRights144A {
      AdditionalInterestDate
      AdditionalInterestRate
      InstrumentId
      LegNumber
      RegistrationPeriodDays
    }
    SourceDocument {
      DocumentEffectiveFromDate
      DocumentSourceTypeCode
      InstrumentId
    }
    TradingRestrictions {
      EffectiveFromDate
      EffectiveToDate
      InstrumentId
      TradingRestrictionCode
      TradingRestrictionCountryIsoCode
    }
    UseOfProceeds {
      InstrumentId
      SettlementDate
      UseOfProceedsAmount
      UseOfProceedsCode
    }
    CoIssuerOrganizationId
    ComissionAgentOrganizationId
    ConversionExchangeAgentOrganizationId
    CustodianOrganizationId
    EscrowAgentOrganizationId
    ExchangeAgentOrganizationId
    InformationAgentOrganizationId
    InvestmentAdvisorOrganizationId
    IssuerOrganizationId
    KeepwellProviderOrganizationId
    ObligorOrganizationId
    OfferRegistrantOrganizationId
    RemarketingAgentOrganizationId
    SelfPlacedOrganizationId
    SukukObligorOrganizationId
    Quotes {
      ObjectId
      Status {
        AdminStatus
        AdminStatusObjectType
        AdminStatusReason
        DeletedFlag
        QuoteId
      }
      Identifier {
        CurrentFlag
        DistributionSourceCode
        GlobalRegionCode
        IdentifierTypeCode
        IdentifierValue
        InstrumentId
        ObjectTypeCode
        QuoteContributorCode
        QuoteCurrencyIsoCode
        QuoteId
        QuoteIsActiveFlag
        QuotePriceSourceCode
      }
    }
  }
}