#Equity Instrument, AllQuote query
#This query takes Instrument PermIDs from the InstrumentList query variable and requests
#basic Instrument Reference Data (name, asset type, status etc), and Instrument Identifiers.
#For each Intrumernt, the querty then requests Quote level reference data and RICs for all quotes
#associated with each Instrument.

query InstrumentRefData($ObjectList: [String!]) {
  EDFInstrument(objectIds: $ObjectList) {
    ObjectId
    Reference {
      InstrumentCommonNames {
        InstrumentNameCommon
        LanguageId
      }
      AssetClassId
      Cfi
      InstrumentStatus
    }
    InstrumentIdentifiers {
      IdentifierTypeId
      IdentifierData {
        IdentifierValue
      }
    }
    IssuerOrganizationId
    AllQuotes {
      ObjectId
      Reference {
        QuoteIsActive
        RetireDate
        QuoteCommonNames {
          QuoteCommonName
          LanguageId
        }
        CountryPrimaryQuoteFlag
        LseOpol
        Mic
        QuoteExchangeCode
        PricingGroupCode
        PricingGroupName
        PrimaryQuoteFlag
        QuoteCountryId
        QuoteCurrencyId
        RoundLotSize
        QuoteRcsAssetClass
        SettlementPeriod
      }
      #The filter on IdentiferTypeId limits results to records with an IdentifierTypeId of 320110 - a RIC
      QuoteIdentifiers(filter: {IdentifierTypeId: {EQ: 320110}}) {
        IdentifierTypeId
        IdentifierData {
          IdentifierValue
          IdentifierEffectiveFrom
        }
      }
    }
  }
}