query Nominal($ObjectList: [String!]) {
  NominalValues(limit:10, filter: {AND: [{UnderlyingInstrumentId: {IN: $ObjectList}}, {EventAdjustment: {EventTypeCode: {EQ: "NOMV"}}}]}) {
    ObjectId
    _metadata {
      totalCount
    }
    EventAdjustment {
      EventTypeCode
    }
    ObjectId
    NominalValue {
      General {
        EventId
        InstrumentId
        NominalValueDate
        NominalValue
        NominalValueCurrencyId
        UnderlyingEventId
        NoParValueFlag
        LastUpdateDate
      }
    }
  }
}